version: '0.0.0.{build}'
image: Visual Studio 2022
platform: Any CPU

environment:
  matrix:
    - BUILD_NPGSQL_VERSION: 5
    - BUILD_NPGSQL_VERSION: 6

init:
- ps: >-
    Set-Content "c:\program files\postgresql\9.6\data\pg_hba.conf" "host    all             all             ::1/128            trust"

    Add-Content "c:\program files\postgresql\9.6\data\pg_hba.conf" "host    all             all             127.0.0.1/32            trust"

    $env:Path += ";c:\program files\postgresql\9.6\bin"
services: postgresql
build_script:
- ps: >-
    psql -U postgres -c "CREATE ROLE appveyor LOGIN SUPERUSER CREATEDB CREATEROLE;"

    createdb hangfire_tests

    .\build.ps1 -t Pack -NpgsqlVersion $env:BUILD_NPGSQL_VERSION
cache:
- tools -> build.cake
- tools -> build.ps1

artifacts:
- path: publish\*.nupkg
  name: NuPkgs

test: off