name: Test report

on:
  workflow_run:
    workflows: ['Verification build', 'Build and tests']
    types:
      - completed

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Test results
        path: "**/TestResults.trx"
        reporter: dotnet-trx
        fail-on-error: false
